## A1. Note di redazione {.unnumbered}

### Un libro Open
La decisione di scrivere un libro _Open_ (cioè liberamente scaricabile, modificabile e riutilizzabile) è innanzitutto una scelta ideologica: sono un convinto sostenitore dell’Open Science da oltre quindici anni e ritengo che, per un testo di questo tipo, sia l’opzione più logica. Gran parte dei libri e delle risorse da cui ho appreso i contenuti che propongo in queste pagine erano, o sono tuttora, liberamente accessibili, e considero questa modalità non solo sensata, ma anche eticamente corretta. Oltre alla dimensione ideologica, un libro _Open_ come questo offre ulteriori vantaggi, che verranno illustrati nel paragrafo seguente.

### Un libro in costante miglioramento
Ho scelto di scrivere un libro in questa modalità, tramite un sito e un .pdf scaricabile associato, perché sono fermamente convinto che (nel 2025, momento in cui sto cominciando a scrivere il volume), bisogna sfruttare tutte le opportunità date dalla tecnologia.
Psicometria e statistica applicate alla neuropsicologia sono anche discipline in costante crescita e un libro pubblicato tramite canali tradizionali rischierebbe di essere obsoleto in alcune sue parti già al momento della pubblicazione. In questa maniera potrò anche migliorarlo costantemente sulla base dei commenti di lettori, professioniste/i e studenti/studentesse. 

### Una nota sul titolo
Il titolo del libro _Oltre i punteggi_ è volto a sottolineare la mia posizione sull'importanza di integrare i punteggi ai test con altre informazioni e non penso abbia bisogno di altre spiegazioni. Il sottitolo del libro invece, per precisione, sarebbe dovuto essere "Elementi di psicometria _e statistica_ per la neuropsicologia clinica". Psicometria e statistica sono infatti due discipline separate (per quanto strettamente connesse) ed entrambi i termini avrebbero meritato di essere presenti. La mia scelta è stata solo di escludere il termine statistica per evitare un sottotitolo troppo lungo e di intimorire troppo. Del resto la materia "Psicometria" per come è insegnata all'Università tratta spesso numerosi elementi di statistica.   

### Femminile e maschile nel testo
In un ottica di gender balance ho deciso di evitare il più possibile di usare solo il maschile nel testo mettendo ogni volta che fosse necessario prima femminile e poi maschile (es. la/il neuropsicologa/o). Questa è una scelta che ho dovuto inevitabilmente fare visto che la prima stesura del testo è in Italiano. Mi rendo conto che questa scelta, per quanto motivata, potrebbe rendere più difficile la lettura. Le evidenze sull'impatto di una scelta come questa nella lettura sono tuttora non chiare e mi sono basato quindi su un criterio più personale che non su evidenze scientifiche.

### Utilizzo di AI nella stesura del libro
Nel momento in cui sto cominciando a scrivere questo libro (Agosto 2025), siamo in piena esplosione dell'utilizzo e delle opportunità di sistemi di Intelligenza Artificiale (In particolare Large Language Models, LLM come ChatGPT). Sta diventando sempre più comune dunque esplicitare che utilizzo se ne è fatto, in maniera trasparente. 
Tutte le idee di questo libro sono generate **senza** l'ausilio di sistemi di intelligenza artificiale.
Sistemi di AI (e in particolare ChatGPT) sono stati utilizzati per i seguenti scopi:

* revisione del testo (per typos o miglioramento chiarezza di alcune frasi)
* supporto nel codice per generare il libro (Quarto e i linguaggi associati).
* generazioni di alcune immagini esemplificativi (questo per evitare problemi di immagini con copyright).
* supporto nella generazione di codice `R` per alcuni esempi.

In ogni caso, mi prendo ogni responsabilità di errori legati all'utilizzo di sistemi di AI.