## Ringraziamenti personali {.unnumbered}
Tutti i ringraziamenti che seguono vanno considerati in ordine sparso, senza una gerarchia particolare.

Ringrazio la mia supervisor di dottorato, la Prof.ssa Sara Mondini, per avermi fatto appassionare alla neuropsicologia clinica e per le numerose interessantissime discussioni. Diverse parti di questo libro sono state sviluppate a partire da scambi con lei e sono almeno in parte state già riportate in altri testi, che abbiamo scritto anche insieme alla Prof.ssa Daniela Mapelli e la Prof.ssa Marinella Cappelletti.

Ringrazio il Prof. Carlo Semenza, per avermi fatto sempre credere nell'importanza di porsi domande, anche quando sembrano controcorrente, e per avermi trasmesso la passione alla neuropsicologia e alla scienza.

Ringrazio tutto il personale clinico con cui ho avuto modo di discutere e collaborare in questi anni. Molto di quanto scritto riflette delle discussioni fatte con loro e il tentativo di rispondere a domande che mi sono state poste proprio da loro. 

Vorrei ringraziare i membri del Quantitative Psychology Lab (QP Lab), del Dipartimento di Psicologia Generale dell'Università di Padova per le discussioni stimolanti e le considerazioni. Varie parti di questo libro sono state sviluppate a partire da scambi con loro, spesso illuminanti. In ordine alfabetico: Giovanni Bruno, Umberto Granziol, Stefano Noventa, Massimo Nucci, Andrea Spoto, Michele Vicovaro.

Grazie a Rachele, per la sua pazienza senza fine.