## Premessa {.unnumbered}

```{r, include = FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

Questa guida ha come obiettivo fornire le conoscenze fondamentali di psicometria da utilizzare nella pratica clinica in neuropsicologia clinica e forense.
A differenza di altri testi disponibili su Psicometria, questo libro si focalizza specificamente ad applicazioni pratiche nella professione. Nel corso dei suoi capitoli sono approfonditi aspetti psicometrici e statistici in maniera che cerca di essere semplice e accessibile, senza però banalizzare la complessità dei problemi. 
Lo scopo è quello di fornire degli strumenti pratici per il clinico in modo da integrare _best practices_ di tipo psicometrico e statistico nella propria pratica professionale. 
Al momento iniziale di scrittura di questo libro è in programma di scrivere due manuali separati ma strettamente connessi. Uno (quello presente) è destinato al clinico e contiene tutti gli elementi fondamentali, ma evita approfondimenti relativi a formule e ad aspetti matematici. Il secondo, più approfondito, è destinato a chiunque voglia approfondire tutti gli aspetti statistici/psicometrici e matematici. Questo secondo libro contiene anche codice in `R` per approfondire gli argomenti di base. 

Ci sono due importanti principi alla base di questo libro che vorrei esplicitare sin dall'inizio:

1. Le conoscenze psicometriche _possono_ essere incorporate nella routine clinica, portando ad un utilizzo più consapevole dei test psicologici e neuropsicologici, delle loro potenzialità e limiti, e quindi ad interpretazioni più motivate e ragionate.
2. Le conoscenze psicometriche _sono solo una parte_ delle conoscenze necessarie per la pratica clinica. Conoscenze teoriche (es. di neuropsicologia cognitiva e clinica) e cliniche (es. su come condurre un colloquio). Questo dovrebbe essere quasi scontato, ma è importante chiarire questo punto per una corretta lettura del libro e dei suoi contenuti.

**Il libro è (e sarà sempre) completamente gratuito**


Il libro è infatti rilasciato con licenza Creative Commons 3.0 (CC BY-NC 3.0). Con questa licenza sei libero di scaricare, stampare e distribuire questo libro. Puoi anche copiare parte dei contenuti e modificarli purché sia citata la fonte di orgine.

Se utilizzi o distribuisci il materiale contenuto in questo libro cita segue:  

_Giorgio Arcara (2025), "Guida alla Psicometria per la neuropsicologia Clinica e Forense", rilasciato sotto licenza CC BY-NC 3.0_

## Indice Provvisorio
Di seguito trovi un indice provvisorio del libro. Questo indice potrà essere modificato sulla base dei feedback ricevuti durante il suo sviluppo.

**1. Introduzione**
  * Il protagonosta del libro: Il test neuropsicologico
  * Filosofia alla base del libro

**2. Elementi di base di statistica per la neuropsicologia**

  * campione e popolazione
  * rappresentatività del campione
  * teorema del limite centrale
  * Il concetto di p-value
  * z-scores

**3. Psicometria per la Neuropsicologia clinica**

  * Teoria Classica dei test
  * Validità ed Affidabilità
  * Tipi di Validità e perché sono importanti
  * Affidabilità
  * Tipi di affidabilità e perché sono importanti
  * Nella pratica clinica: Come usare Affidabilità e Validità nella pratica clinica per scegliere i test
  * Nella pratica clinica: Come usare Affidabilità e Validità per interpretare i test

**4. Identificare Deficit e danni cognitivi**

  * il concetto di _deficit_ e i di _danno_
  * il concetto di _deficit_ in età evolutiva
  * cut-off clinici e dati normativi
    * cosa sono i dati normativi
    * come si ottengono i dati normativi
    * cut-off a partire dai dati normativi
  * Metodi per calcolare i cut-offs
    * z-score e percentili
    * metodi basati su regressione
        * I Punteggi Equivalenti (Capitani, 1987)
        * Il metodo di Crawford & Howell per il caso singolo
    * altri metodi
  * Approfondimento: Perché usiamo i cut-off basati su soggetti normali?
  * Approfondimento pratico, il MoCA nella versione originale di Nasreddine
  
**5. Identificare patologie o condizioni di interesse**
  * il gold standard in neuropsicologia clinica e forense
  * Sensibilità, Specificità e la curva ROC.
  * Altre misure di performance.
  
**6. Indagare cambiamenti nel tempo** 

  * errori comuni nell'indagare cambiamenti nel tempo
  * affidabilità test-retest e importanza per studiare cambiamenti nel tempo
  * forme parallele
  * effetto pratica
  * Reliable Change Index e altri metodi per cambiamenti nel tempo.
  
**7. Confrontare punteggi a test diversi**

 * utilizzo di z-score o percentili.
 * Punteggi Equivalenti.
 
**Appendice**

 * Definizioni
 * Statistica di base per il neuropsicologo clinico e forense.
